version: '3'
services:
  api-gateway:
    build: ./
    ports:
      - 8888:8888

    networks:
      - my-network

  service1:
    build: ./service1
    networks:
      - my-network

  service2:
    build: ./service2
    networks:
      - my-network

networks:
  my-network: