Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo
    NAT:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo
    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo  
    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo  
    OrderService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo 
    CustomerService:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
            Parameters:
                EnvironmentName: msdemo                   

Outputs:
    LoadBalancerUrl: 
        Description: Load balancer url
        Value: !GetAtt ALB.Outputs.ExternalUrl
