version: '3.5' # specify docker-compose version

# Define the services/containers to be run
services:
  angular-service: # name of the first service
    container_name: angular-container
    build: ./ # specify the directory of the Dockerfile
    volumes: # Volume binding
      - './:/usr/src/app'
    ports:
      - "4200:4200" # specify port forewarding
    command: >
      bash -c "npm start"
  docker-nginx:
     container_name: docker-nginx
     build: ./
     ports:
         - "80:80"
     command: ["nginx", "-g", "daemon off;"]
     links:
         - angular-service

#version: '3.1'
#services:
#  angular-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "4200:4200"
