#version: "3.9"
#services:
#  web:
#    build: .
#    ports:
#      - "8082:8082"
#    depends_on:
#      - redis
#      - db
#  db:
#    image: mongo
#    hostname: mongodb
#    ports:
#      - "27017:27017"
version: "3.1"
services:
  redis:
    image : "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - redis
