version: '3.1'

services:

  redis:
    container_name: redis
    image : redis
    ports:
      - "6379:6379"

  sec-service:
    container_name: sec-service
    image: sec-service
    build:
      context: ./sec-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - redis

  customer-service:
    container_name: customer-service
    image: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis

  auth-jwt-service:
    container_name: auth-jwt-service
    image: auth-jwt-service
    build:
      context: ./auth-jwt-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"

  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://sec-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: r1
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /auth-service/*
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[1]: DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://sec-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: r2
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /auth-service/myData
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://customer-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: r3
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path= /customer-service/**
      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[1]: DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: http://auth-jwt-service:8086
      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: r4
      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: Path= /auth-jwt-service/**
      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[0]: StripPrefix=1
      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[1]: DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  web-angular: # name of the first service
    container_name: web-angular
    image: web-angular
    build:
      context: ./front-web-ang
      dockerfile: Dockerfile
    volumes: # Volume binding
      - './:/usr/src/app'
    ports:
      - "4200:4200" # specify port forewarding
    command: >
      bash -c "npm start"    

  docker-nginx:
    container_name: docker-nginx
    build:
      context: ./front-web-ang
      dockerfile: Dockerfile
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    links:
      - web-angular